"""tables

Revision ID: fd361f51fb21
Revises: 
Create Date: 2022-05-04 23:47:31.129323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd361f51fb21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player__game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('game_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Scenario_NUmber', sa.String(length=50), nullable=True),
    sa.Column('Category_Person', sa.LargeBinary(), nullable=True),
    sa.Column('Prompt', sa.String(length=50), nullable=True),
    sa.Column('Option_1', sa.String(length=50), nullable=True),
    sa.Column('Option_2', sa.String(length=50), nullable=True),
    sa.Column('Stat_Change_1', sa.String(length=50), nullable=True),
    sa.Column('Stat_change_2', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario')
    op.drop_table('player__game')
    # ### end Alembic commands ###
